# Generated by Django 3.2.3 on 2021-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerName', models.CharField(max_length=255, verbose_name='Имя призывателя')),
                ('profileIconId', models.IntegerField(verbose_name='ico')),
                ('summonerLevel', models.IntegerField(verbose_name='lvl')),
                ('puuid', models.CharField(max_length=255, verbose_name='puuid')),
                ('accountId', models.CharField(max_length=255, verbose_name='accountId')),
                ('mainid', models.CharField(max_length=255, verbose_name='id')),
                ('jsonacc', models.JSONField(verbose_name='jsonacc')),
                ('jsonrank', models.JSONField(verbose_name='jsonrank')),
                ('jsonclash', models.JSONField(verbose_name='jsonclash')),
                ('jsonspec', models.JSONField(verbose_name='jsonclash')),
            ],
        ),
    ]
