# Generated by Django 3.2.3 on 2021-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_summonerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerinfo',
            name='slug',
            field=models.SlugField(default='SummonerName=', unique=True),
            preserve_default=False,
        ),
    ]
